# Generated by Django 3.1.7 on 2021-04-05 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedentitymodel',
            name='subscription_end_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 9, 25, 24, 49565)),
        ),
        migrations.AlterField(
            model_name='subscribedentitymodel',
            name='subscription_start_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 20, 9, 25, 24, 49502)),
        ),
    ]
