# Generated by Django 3.1.7 on 2021-04-05 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_accounts', '0002_auto_20210405_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedentitymodel',
            name='subscription_end_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 9, 37, 20, 411509)),
        ),
        migrations.AlterField(
            model_name='subscribedentitymodel',
            name='subscription_start_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 20, 9, 37, 20, 411462)),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='user_type',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'company_user'), ('3', 'individual_user')], default=3, max_length=5),
        ),
    ]
