# Generated by Django 3.1.7 on 2021-04-05 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_accounts', '0003_auto_20210405_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedentitymodel',
            name='subscription_end_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 9, 43, 11, 404354)),
        ),
        migrations.AlterField(
            model_name='subscribedentitymodel',
            name='subscription_start_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 20, 9, 43, 11, 404310)),
        ),
        migrations.AlterField(
            model_name='subscriptionplanmodel',
            name='amount_type',
            field=models.CharField(choices=[('1', 'INR'), ('2', 'USD')], default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='subscriptionplanmodel',
            name='duration_type',
            field=models.CharField(choices=[('1', 'Day'), ('2', 'Month'), ('3', 'Year')], default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='subscriptionplanmodel',
            name='subscription_plan',
            field=models.CharField(max_length=100, unique=True, verbose_name='Plan Name'),
        ),
        migrations.AlterField(
            model_name='subscriptionplanmodel',
            name='subscription_type',
            field=models.CharField(choices=[('1', 'Company'), ('2', 'Individual User')], default=2, max_length=100),
        ),
    ]
